substitutions:
  display_refresh_delay: 50ms

esphome:
  name: kitchen-display
  friendly_name: Kitchen Display
  build_flags:
    - -DBOARD_HAS_PSRAM

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 8MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_PERF: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: "y"
      CONFIG_FREERTOS_HZ: "1000"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"
      CONFIG_SPIRAM_RODATA: "y"

psram:
  mode: octal
  speed: 80MHz

logger:

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

<<: !include kitchen-common.yaml

i2c:
  id: display_i2c
  sda: GPIO8
  scl: GPIO9
  frequency: 400kHz
  scan: true

waveshare_io_ch32v003:
  - id: display_io
    address: 0x24
    i2c_id: display_i2c

output:
  - platform: gpio
    id: lcd_backlight_output
    pin:
      waveshare_io_ch32v003: display_io
      number: 2
      mode: OUTPUT
      inverted: false

light:
  - platform: binary
    id: lcd_backlight
    name: Kitchen Display Backlight
    output: lcd_backlight_output
    restore_mode: ALWAYS_ON

display:
  - platform: mipi_rgb
    model: RPI
    id: main_display
    dimensions:
      width: 1024
      height: 600
    color_order: RGB
    update_interval: never
    auto_clear_enabled: false
    pclk_frequency: 30MHz
    pclk_inverted: true
    de_pin: GPIO5
    hsync_pin:
      number: GPIO46
      ignore_strapping_warning: true
    vsync_pin:
      number: GPIO3
      ignore_strapping_warning: true
    pclk_pin: GPIO7
    reset_pin:
      waveshare_io_ch32v003: display_io
      number: 3
      mode: OUTPUT
    hsync_back_porch: 152
    hsync_front_porch: 48
    hsync_pulse_width: 162
    vsync_back_porch: 13
    vsync_front_porch: 3
    vsync_pulse_width: 45
    data_pins:
      red:
        - GPIO1
        - GPIO2
        - GPIO42
        - GPIO41
        - GPIO40
      green:
        - GPIO39
        - GPIO0
        - GPIO45
        - GPIO48
        - GPIO47
        - GPIO21
      blue:
        - GPIO14
        - GPIO38
        - GPIO18
        - GPIO17
        - GPIO10

touchscreen:
  - platform: gt911
    id: main_touchscreen
    display: main_display
    i2c_id: display_i2c
    interrupt_pin: GPIO4
    reset_pin:
      waveshare_io_ch32v003: display_io
      number: 1
      mode: OUTPUT
